CREATE TABLE IF NOT EXISTS blips (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  label VARCHAR(50) NOT NULL,
  sprite INT NOT NULL,
  scale FLOAT NOT NULL,
  color INT NOT NULL,
  x FLOAT NOT NULL,
  y FLOAT NOT NULL,
  z FLOAT NOT NULL,
  jobOnly TINYINT(1) DEFAULT 0,
  jobName VARCHAR(50) DEFAULT NULL
);